#!/usr/bin/env bash

###
# 
# @File   : no-head   
# @Author : jiachen.zou@jiiov.com   
# @Date   : 2021-03-15 17:55 CST(+0800)   
# @Brief  : print ignored part by 'head'
# 
###

prog="$0"

cmd=tail
opt=

ErrorExit() {
    echo "$prog: $1" >&2
    exit 1
}

CheckSetting() {
    if [[ "$opt" ]]
    then
        ErrorExit "conflict option '$1'."
    fi
}

while [[ "$1" == '-'* ]]
do
    if [[ "$1" == '-h' || "$1" == '--help' ]]
    then
        echo "Usage: $prog [-f | -F] [-q] [-n LINES | -c BYTES] [FILE ...]"
        exit 255
    elif [[ "$1" == '--' ]]
    then
        shift
        break
    elif [[ "$1" =~ ^-[Ffq]$ ]]
    then
        cmd="$cmd $1"
        shift
    elif [[ "$1" == '-n' ]]
    then
        CheckSetting "$1"
        if [[ "$2" =~ ^[0-9]+$ && "$2" -ne 0 ]]
        then
            n="$2"
            opt="-n+$((n+1))"
            shift 2
        else
            ErrorExit "invalid count '$2'."
        fi
    elif [[ "$1" =~ ^-n[0-9]+$ && "${1:2}" -ne 0 ]]
    then
        CheckSetting "$1"
        n="${1:2}"
        opt="-n+$((n+1))"
        shift
    elif [[ "$1" == '-c' ]]
    then
        CheckSetting "$1"
        if [[ "$2" =~ ^[0-9]+$ && "$2" -ne 0 ]]
        then
            n="$2"
            opt="-c+$((n+1))"
            shift 2
        else
            ErrorExit "invalid count '$2'."
        fi
    elif [[ "$1" =~ ^-c[0-9]+$ && "${1:2}" -ne 0 ]]
    then
        CheckSetting "$1"
        n="${1:2}"
        opt="-c+$((n+1))"
        shift
    elif [[ "$1" =~ ^-[0-9]+$ && "${1:1}" -ne 0 ]]
    then
        CheckSetting "$1"
        n="${1:1}"
        opt="-n+$((n+1))"
        shift
    else
        ErrorExit "invalid option '$1'."
    fi
done

if [[ "$opt" ]]
then
    cmd="$cmd $opt"
fi

$cmd "$@"

# End of 'no-head' 

