#!/bin/bash

###
# Copyright (c) 2011 Baidu.com, Inc. All Rights Reserved
# 
# @File   : show_colors   
# @Author : zoujiachen@baidu.com   
# @Date   : 2011-11-23 15:26   
# @Brief  :  
# 
###

echo
echo 'SET : \033[$i;$jm        UNSET: \033[0m'
echo

printf '$i \\ $j\t'
for((j=1;j<9;j++))
do
	printf '   %s\t' $j
done
printf '\n'

for((i=30;i<50;i++))
do
	printf '  %s\t' $i
	for((j=1;j<9;j++))
	do
		printf ' \033[%s;%sm%s;%s\033[0m\t' $i $j $i $j
	done
	printf '\n'
done

echo

# End of 'show_colors' 

