#!/bin/bash

###
# 
# @File   : slink
# @Author : zoujiachen@megvii.com   
# @Date   : 2019-05-31 11:23   
# @Brief  : Much like "ln -s" but fills path according to destination
# @Usage  : see "slink -h"
# 
###

prog="$0"

Usage() {
    echo 'USAGE:'
    echo -e "\t${prog} [-h]"
    echo -e "\t${prog} [-a] \033[4mSOURCE\033[0m... \033[4mTARGET\033[0m"
    echo
    echo 'DESCRIPT:'
    echo -e "\tCreate symbolic link(s) of each \033[4mSOURCE\033[0m to/into \033[4mTARGET\033[0m."
    echo -e "\tCreated link(s) will contain path relative to the \033[4mTARGET\033[0m directory."
    echo
    echo 'OPTIONS:'
    echo -e "\t-a\tforce using absolute path."
    echo -e "\t-f\toverwrite existing files."
    echo -e "\t-h\tshow this message."
    echo
    exit 1
}

Fullpath() {
    dir="$(dirname "$1")"
    file="$(basename "$1")"
    if [[ -d "$dir" ]]
    then
        fullpath="$(cd "$dir" && pwd)/$file"
        if [[ $? -eq 0 ]]
        then
            if [[ -d "$fullpath" ]]
            then # in case '$file' is '.' or '..'
                tmp=$(cd "$fullpath" && pwd)
                if [[ $? -eq 0 ]]
                then
                    fullpath="$tmp"
                fi
            fi
            echo "$fullpath"
        fi
    fi
}

# get $1's path relative to $2
RelaPath() {
    path="$1"
    base="$2"
    if [[ ! -d "$base" ]]
    then
        base="$(dirname "$base")"
    fi
    result=
    while [[ "$path" != "${base}"* ]]
    do
        result="../${result}"
	    base="$(dirname "$base")"
    done
    if [[ "$base" != "*/" && "$base" != "/" ]]
    then
	    base="$base/"
    fi
    result="${result}${path#$base}"
    echo "$result"
}

force_overwrite=
force_fullpath=

while [[ "$#" -ge 1 && "${1:0:1}" = '-' ]]
do
    arg="$1"
    shift
    if [[ "$arg" = '-a' ]]
    then
        force_fullpath=yes
    elif [[ "$arg" = '-f' ]]
    then
        force_overwrite=yes
    elif [[ "$arg" = '-h' ]]
    then
        Usage
    elif [[ "$arg" = '--' ]]
    then
        break
    else
        echo "${prog}: unknown argument '$arg', see '${prog} -h' for instructions." >&2
        exit 100
    fi
done

if [[ "$#" -lt 2 ]]
then
    echo "${prog}: need more arguments to proceed, see '${prog} -h' for instructions." >&2
    exit 101
fi

dst="${@:$#:1}"
src_count="$(($#-1))"

dst_is_dir=
if [[ -d "$dst" ]]
then
    dst_is_dir=yes
fi

if [[ "$src_count" -gt 1 && -z "$dst_is_dir" ]]
then
    echo "${prog}: '${dst}' is not a directory, see '${prog} -h' for instructions." >&2
    exit 102
fi

full_dst="$(Fullpath "$dst")"
if [[ -z "$full_dst" ]]
then
    echo "${prog}: invalid target path: '${dst}'" >&2
    exit 103
fi

while [[ "$#" -ge 2 ]]
do
    src="$1"
    shift
    full_src="$(Fullpath "$src")"

    # check for source existence:
    if [[ -z "$full_src" ]]
    then
        echo "${prog}: invalid source path: '${src}'" >&2
        exit 104
    fi

    # check for destination existence:
    if [[ "$dst_is_dir" ]]
    then
        real_dst="$dst/$(basename $src)"
    else
        real_dst="$dst"
    fi

    # Note: $full_dst is absolute path of $dst,
    #       $real_dst is $dst with necessary filename completion.
    if [[ -e "$real_dst" || -L "$real_dst" ]]
    then
        if [[ "$force_overwrite" ]]
        then
            rm -rf "$real_dst"
            if [[ $? -ne 0 ]]
            then
                exit $?
            fi
        else
            echo "file '$real_dst' exists, overwrite it? [Y/n]" >&2
            read line
            if [[ "${#line}" -ne 0 && "${line:0:1}" != 'y' && "${line:0:1}" != 'Y' ]]
            then
                echo "file '$real_dst' skipped." >&2
                continue
            else
                rm -rf "$real_dst"
                if [[ $? -ne 0 ]]
                then
                    exit $?
                fi
            fi # user enter Y or N
        fi # $force_overwrite
    fi # $dst exists

    if [[ "$force_fullpath" ]]
    then
        ln -s "$full_src" "$dst"
        if [[ "$?" -ne 0 ]]
        then
            exit $?
        fi
    else
        rela_path="$(RelaPath "$full_src" "$full_dst")"
        ln -s "$rela_path" "$dst"
        if [[ "$?" -ne 0 ]]
        then
            exit $?
        fi
    fi
done

# End of 'slink' 

