#!/bin/bash

# by zoujiachen@baidu.com
# 2011-11-11 (such a beautiful day !!)

# Change Log:
# 2018-09-14 add more header for c++11/14/17

EDITOR="vim"
COMPILER="g++ -o"

MY_NAME="$0"
CMD="$1"
shift
OPTIONS="$*"
MY_TTY="`tty`"
MY_TTY=`basename "$MY_TTY"`
TEMP_DIR="$HOME/.cpp-run"
WORK_DIR="$TEMP_DIR/$MY_TTY"
SOURCE_FILE="$WORK_DIR/source.cpp"
TARGET_FILE="$WORK_DIR/a.out"

NO_EDIT=""

CPP_STD="03"
for opt in $OPTIONS
do
	if [ "$opt" == '-std=c++11' ]
	then
		CPP_STD=11
	elif [ "$opt" == '-std=c++14' ]
	then
		CPP_STD=14
	elif [ "$opt" == '-std=c++17' ]
	then
		CPP_STD=17
	fi
done

Help() {
	echo -e
	echo -e "Open $EDITOR for you to write short C++ code, then compile & run it immediately."
	echo -e
	echo -e "USAGE:"
	echo -e "\\t\\t$MY_NAME COMMAND [G++_OPTIONS]"
	echo -e
	echo -e "COMMAND:"
	echo -e "\\t\\tnew\\t- start from an empty pattern"
	echo -e "\\t\\tlast\\t- continue with source file saved last time"
	echo -e "\\t\\tagain\\t- compile & run last program again directly"
	echo -e "\\t\\tpath\\t- show path of source file"
	echo -e "\\t\\thelp\\t- show this information"
	echo -e
	echo -e "G++_OPTIONS:"
	echo -e "\\t\\tall other options will pass to compiler"
	echo -e
	exit 1
}

Question() {
	while [[ 1 ]]
	do
		Print 'PINK' "$1"
		default_value="$2"
		read line
		if [ "${#default_value}" -gt '0' -a "${#line}" -eq '0' ]
		then
			return $default_value
		fi
		case "${line:0:1}" in
			y|Y )	return 1;;
			n|N )	return 0;;
		esac
	done
}

Print() {
	local color="$1"
	shift
	case "$color" in
		GRAY	) color="30";;
		RED		) color="31";;
		GREEN	) color="32";;
		YELLOW	) color="33";;
		BLUE	) color="34";;
		PINK	) color="35";;
		LBLUE	) color="36";;
		WHITE	) color="37";;
		BLACK	) color="38";;
		*		) color="00";;
	esac
	printf '\033[%s;1m%s\033[0m\n' "$color" "$*"
}

NewFile() {
	Print 'LBLUE' "Creating new file ..."
	mkdir -p "$WORK_DIR"
	if [ "$?" -ne "0" ]
	then
		Print 'RED' "ERROR: fail to create tempory directory, try 'rm -rf $TEMP_DIR' to fix it." >&2
	fi
	if [ -f "$SOURCE_FILE" ]
	then
		now=$(date '+%s')
		ts=$(date -r "$SOURCE_FILE" '+%s')
		if [ "$(($now - $ts < 24 * 60 * 60))" -ne 0 ]
		then
			Question 'Sure to OVERWRITE your code with new file? [Y/n]' 1
			if [ "$?" -eq 0 ]
			then
				Print 'YELLOW' 'Canceled.'
				exit 1
			fi
		fi
	fi
	rm -rf $WORK_DIR/*
	# Template Here :
	echo '#include <iostream>' >> "$SOURCE_FILE"
	echo '#include <string>' >> "$SOURCE_FILE"
	echo '#include <bitset>' >> "$SOURCE_FILE"
	echo '#include <vector>' >> "$SOURCE_FILE"
	echo '#include <list>' >> "$SOURCE_FILE"
	echo '#include <deque>' >> "$SOURCE_FILE"
	echo '#include <queue>' >> "$SOURCE_FILE"
	echo '#include <set>' >> "$SOURCE_FILE"
	echo '#include <map>' >> "$SOURCE_FILE"
	echo '#include <algorithm>' >> "$SOURCE_FILE"
	echo '#include <memory>' >> "$SOURCE_FILE"
	echo '#include <new>' >> "$SOURCE_FILE"
	echo '#include <complex>' >> "$SOURCE_FILE"
	echo '#include <exception>' >> "$SOURCE_FILE"
	echo '#include <functional>' >> "$SOURCE_FILE"
	echo '#include <utility>' >> "$SOURCE_FILE"
	echo '#include <typeinfo>' >> "$SOURCE_FILE"
	if [ "$CPP_STD" -ge 11 ]
	then
		echo '#include <chrono>' >> "$SOURCE_FILE"
		echo '#include <codecvt>' >> "$SOURCE_FILE"
		echo '#include <initializer_list>' >> "$SOURCE_FILE"
		echo '#include <array>' >> "$SOURCE_FILE"
		echo '#include <forward_list>' >> "$SOURCE_FILE"
		echo '#include <unordered_set>' >> "$SOURCE_FILE"
		echo '#include <unordered_map>' >> "$SOURCE_FILE"
		echo '#include <random>' >> "$SOURCE_FILE"
		echo '#include <ratio>' >> "$SOURCE_FILE"
		echo '#include <regex>' >> "$SOURCE_FILE"
		echo '#include <tuple>' >> "$SOURCE_FILE"
		echo '#include <thread>' >> "$SOURCE_FILE"
		echo '#include <mutex>' >> "$SOURCE_FILE"
		echo '#include <condition_variable>' >> "$SOURCE_FILE"
		echo '#include <future>' >> "$SOURCE_FILE"
		echo '#include <atomic>' >> "$SOURCE_FILE"
	fi
	if [ "$CPP_STD" -ge 17 ]
	then
		echo '#include <optional>' >> "$SOURCE_FILE"
		echo '#include <any>' >> "$SOURCE_FILE"
		echo '#include <filesystem>' >> "$SOURCE_FILE"
		echo '#include <variant>' >> "$SOURCE_FILE"
		echo '#include <shared_mutex>' >> "$SOURCE_FILE"
		echo '#include <string_view>' >> "$SOURCE_FILE"
	fi
	if [ "$CPP_STD" -ge 20 ]
	then
		echo '#include <compare>' >> "$SOURCE_FILE"
		echo '#include <version>' >> "$SOURCE_FILE"
	fi
	echo >> "$SOURCE_FILE"
	echo '#include <cstdio>' >> "$SOURCE_FILE"
	echo '#include <cstdlib>' >> "$SOURCE_FILE"
	echo '#include <cstdint>' >> "$SOURCE_FILE"
	echo '#include <cstring>' >> "$SOURCE_FILE"
	echo '#include <climits>' >> "$SOURCE_FILE"
	echo '#include <cerrno>' >> "$SOURCE_FILE"
	echo '#include <ctime>' >> "$SOURCE_FILE"
	echo '#include <csignal>' >> "$SOURCE_FILE"
	echo '#include <csetjmp>' >> "$SOURCE_FILE"
	echo >> "$SOURCE_FILE"
	echo '#include <unistd.h>' >> "$SOURCE_FILE"
	echo '#include <fcntl.h>' >> "$SOURCE_FILE"
	echo '#include <sys/types.h>' >> "$SOURCE_FILE"
	echo '#include <sys/stat.h>' >> "$SOURCE_FILE"
	echo '#include <sys/socket.h>' >> "$SOURCE_FILE"
	echo '#include <sys/time.h>' >> "$SOURCE_FILE"
	echo >> "$SOURCE_FILE"
	echo 'using namespace std;' >> "$SOURCE_FILE"
	echo >> "$SOURCE_FILE"
	echo 'int main()' >> "$SOURCE_FILE"
	echo '{' >> "$SOURCE_FILE"
	echo '	return 0;' >> "$SOURCE_FILE"
	echo '}' >> "$SOURCE_FILE"
	echo >> "$SOURCE_FILE"
}

case "$CMD" in
	help )	Help;;
	new  )	NewFile;;
	last )	if [ ! -f "$SOURCE_FILE" ]
			then
				Print 'LBLUE' "no old source file found."
				NewFile
			fi;;
	again)	if [ ! -f "$SOURCE_FILE" ]
			then
				Print 'LBLUE' "no old source file found."
				NewFile
			fi
			NO_EDIT="yes";;
	path )  if [ ! -f "$SOURCE_FILE" ]
			then
				Print 'RED' "no old source file found."
				exit 1
			else
				Print 'LBLUE' "$SOURCE_FILE"
				exit 0
			fi;;
	* )		Print 'RED' "ERROR: you need to provide a command, see '$MY_NAME help' for help." >&2
			exit 1;;
esac

if [ ! "$NO_EDIT" ]
then
	START_LINE=$(egrep -n '^\s*int\s+main\s*\(' "$SOURCE_FILE" | egrep -o '^\d+')
	if [ "$?" -ne '0' ]
	then
		START_LINE=1
	else
		START_LINE=$((START_LINE+2))
	fi
	if [ "$EDITOR" == "vi" -o "$EDITOR" == "vim" -o "$EDITOR" == "gvim" ]
	then
		$EDITOR "$SOURCE_FILE" "+$START_LINE"
	else
		$EDITOR "$SOURCE_FILE"
	fi
	ret="$?"
	if [ "$ret" -ne "0" ]
	then
		Print 'RED' "ERROR: editor($EDITOR) returned $ret." >&2
		exit "$ret"
	fi
fi

Print 'LBLUE' "Compiling ..."
rm -rf "$TARGET_FILE"
$COMPILER "$TARGET_FILE" "$SOURCE_FILE" $OPTIONS
ret="$?"
if [ "$ret" -ne "0" ]
then
	Print 'RED' "ERROR: compiler($COMPILER) returned $ret." >&2
	exit "$ret"
fi

if [ ! -x "$TARGET_FILE" ]
then
	Print 'RED' "ERROR: cannot found executable binary created by compiler." >&2
	exit 1
fi

args=""
if [ "`egrep -o '(^|\\s)main\\s*\\(.*,.*\\)' \"$SOURCE_FILE\" 2> /dev/null`" ]
then
	Print 'LBLUE' "Please enter arguments for launching your program:"
	read args
fi

Print 'LBLUE' "Launching ..."
Print 'YELLOW' "================= OUTPUT ================="
bash -c "\"$TARGET_FILE\" $args"
ret="$?"
Print 'YELLOW' "=========================================="
if [ "$ret" -ne "0" ]
then
	Print 'RED' "WARNING: your program returned $ret." >&2
	exit "$ret"
fi

Print 'LBLUE' "DONE"

