#!/bin/bash

###
# Copyright (c) 2019 Face++, Megvii. All Rights Reserved
# 
# @File   : ratio   
# @Author : zoujiachen@megvii.com   
# @Date   : 2019-03-21 15:19   
# @Brief  :  
# 
###


PROGRAM="$0"
sep=' '

Help()
{
	echo -en "Usage:\t"
	echo     "$PROGRAM N M	# Print irreducible fraction of N/M "
	echo -en "\t"
	echo     "$PROGRAM N:M	# Same as above"
	echo -en "\t"
	echo     "$PROGRAM N/M	# Same as above"
	echo
	echo -e "Note:\tN and M must both be POSITIVE INTEGER."
	exit 1
}

Gcd()
{
	if [ $2 -eq 0 ]
	then
		echo $1
	else
		Gcd $2 $(($1 % $2))
	fi
}

Process()
{
	N=$1
	M=$2
	if [ $N -le 0 -o $M -le 0 ]
	then
		Help
	fi
	gcd=`Gcd $N $M`
	N=$(($N / $gcd))
	M=$(($M / $gcd))
	echo "${N}${sep}${M}"
	exit 0
}

if [ $# -eq 1 ]
then
	echo "$1" | egrep -o '^[0-9]+[/: \t][0-9]+$' > /dev/null
	if [ $? -eq 0 ]
	then
		N=$(echo "$1" | egrep -o '^[0-9]+')
		M=$(echo "$1" | egrep -o '[0-9]+$')
		sep=$(echo "$1" | egrep -o '[^0-9]')
		Process $N $M
	fi
elif [ $# -eq 2 ]
then
	echo "$1" | egrep -o '^[0-9]+$' > /dev/null && \
	echo "$2" | egrep -o '^[0-9]+$' > /dev/null
	if [ $? -eq 0 ]
	then
		Process $1 $2
	fi
elif [ $# -eq 3 ]
then
	if [ "$2" == ':' -o "$2" == '/' ]
	then
		echo "$1" | egrep -o '^[0-9]+$' > /dev/null && \
		echo "$3" | egrep -o '^[0-9]+$' > /dev/null
		if [ $? -eq 0 ]
		then
			sep=$2
			Process $1 $3
		fi
	fi
fi

Help

# End of 'ratio' 

